
services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  web:
    build: .
    container_name: web
    command: sh -c "npm start"
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/Song
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
